# language: node_js
# node_js:
#  - "8"
# dist: trusty
# sudo: false

# cache:
#  directories:
#    - node_modules

# addons:
#  chrome: stable

# script:
#  - npm run lint
# #  - npm run test:headless
#  - npm run build
# #  - xvfb-run npm run e2e

language: node_js
node_js:
 - "8.10"

branches:
  only:
    - master


addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng build --prod
  - ng lint


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  on: